def main():
    user_input = input("Input: ")
    morsecode = words_to_morsecode(user_input)
    print("Output: " + morsecode)

def words_to_morsecode(user_input):
    '''
    Each word character corresponds to a set of dashes and lines in morsecode
    '''
    user_input = user_input.replace('A', '.- ')
    user_input = user_input.replace('B', '-... ')
    user_input = user_input.replace('C', '-.-. ')
    user_input = user_input.replace('D', '-.. ')
    user_input = user_input.replace('E', '. ')
    user_input = user_input.replace('F', '..-. ')
    user_input = user_input.replace('G', '..-. ')
    user_input = user_input.replace('H', '..-. ')
    user_input = user_input.replace('I', '.. ')
    user_input = user_input.replace('J', '.--- ')
    user_input = user_input.replace('K', '-.- ')
    user_input = user_input.replace('L', '.-.. ')
    user_input = user_input.replace('M', '-- ')
    user_input = user_input.replace('N', '-. ')
    user_input = user_input.replace('O', '--- ')
    user_input = user_input.replace('P', '.--. ')
    user_input = user_input.replace('Q', '--.- ')
    user_input = user_input.replace('R', '.-. ')
    user_input = user_input.replace('S', '... ')
    user_input = user_input.replace('T', '- ')
    user_input = user_input.replace('U', '..- ')
    user_input = user_input.replace('V', '...- ')
    user_input = user_input.replace('W', '.-- ')
    user_input = user_input.replace('X', '-..- ')
    user_input = user_input.replace('Y', '-.-- ')
    user_input = user_input.replace('Z', '--.. ')

    user_input = user_input.replace('a', '.- ')
    user_input = user_input.replace('b', '-... ')
    user_input = user_input.replace('c', '-.-. ')
    user_input = user_input.replace('d', '-.. ')
    user_input = user_input.replace('e', '. ')
    user_input = user_input.replace('f', '..-. ')
    user_input = user_input.replace('g', '..-. ')
    user_input = user_input.replace('h', '..-. ')
    user_input = user_input.replace('i', '.. ')
    user_input = user_input.replace('j', '.--- ')
    user_input = user_input.replace('k', '-.- ')
    user_input = user_input.replace('l', '.-.. ')
    user_input = user_input.replace('m', '-- ')
    user_input = user_input.replace('n', '-. ')
    user_input = user_input.replace('o', '--- ')
    user_input = user_input.replace('p', '.--. ')
    user_input = user_input.replace('q', '--.- ')
    user_input = user_input.replace('r', '.-. ')
    user_input = user_input.replace('s', '... ')
    user_input = user_input.replace('t', '- ')
    user_input = user_input.replace('u', '..- ')
    user_input = user_input.replace('v', '...- ')
    user_input = user_input.replace('w', '.-- ')
    user_input = user_input.replace('x', '-..- ')
    user_input = user_input.replace('y', '-.-- ')
    user_input = user_input.replace('z', '--.. ')

    user_input = user_input.replace('1', '.---- ')
    user_input = user_input.replace('2', '..--- ')
    user_input = user_input.replace('3', '...-- ')
    user_input = user_input.replace('4', '....- ')
    user_input = user_input.replace('5', '..... ')
    user_input = user_input.replace('6', '-.... ')
    user_input = user_input.replace('7', '--... ')
    user_input = user_input.replace('8', '---.. ')
    user_input = user_input.replace('9', '----. ')
    user_input = user_input.replace('0', '----- ')

    user_input = user_input.replace(' ', '/ ')
    return user_input


if __name__ == '__main__':
    main()
